version: '3.2'
services:
  postgres:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - ../docker-volumes/crypto-rates-test/pg/data:/var/lib/postgresql/data

  service: 
    build: .
    image: price-service
    ports:
      - 3000:3000
    environment:
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
    depends_on:
      - postgres
